name: Make resume PDF
on:
  push:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: make pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          resume-onepage/cv_12.tex
    - name: save pdf
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: main.pdf